"""Initial table

Revision ID: a883ad67d6aa
Revises: 
Create Date: 2025-04-26 18:17:16.475153

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a883ad67d6aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pair', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('mms_20', sa.Float(), nullable=True),
    sa.Column('mms_50', sa.Float(), nullable=True),
    sa.Column('mms_200', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mms_pair'), 'mms', ['pair'], unique=False)
    op.create_index(op.f('ix_mms_timestamp'), 'mms', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mms_timestamp'), table_name='mms')
    op.drop_index(op.f('ix_mms_pair'), table_name='mms')
    op.drop_table('mms')
    # ### end Alembic commands ###
